[package]
name = "mech-syntax"
version = "0.0.1"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "A toolchain for compiling textual syntax into Mech blocks."
documentation = "http://mech-lang.org/page/learn/"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/syntax"
keywords = ["mech", "language", "programming", "parser", "compiler"]
categories = ["no-std", "science::robotics", "science", "parser-implementations"]
license = "Apache-2.0"
readme = "README.md"

[badges]
gitlab = { repository = "mech-lang/syntax", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
no-std = ["mech-core/no-std", "libc"]

[dependencies]
mech-core = {git = "https://gitlab.com/mech-lang/core"}
hashbrown = "0.1.8"
nom = "4.2.2"
libc = { version = "0.2.54", optional = true }