[package]
name = "mech-syntax"
version = "0.0.1"
authors = ["Corey Montella <corey@mech-lang.org>"]

[dependencies]
mech-core = {git = "https://gitlab.com/mech-lang/core"}
hashbrown = "0.1.8"
nom = "4.2.2"